# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import hello_pb2 as hello__pb2


class HelloStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Say = channel.unary_unary(
        '/hello.Hello/Say',
        request_serializer=hello__pb2.HelloRequest.SerializeToString,
        response_deserializer=hello__pb2.HelloReply.FromString,
        )
    self.Notify = channel.unary_stream(
        '/hello.Hello/Notify',
        request_serializer=hello__pb2.HelloRequest.SerializeToString,
        response_deserializer=hello__pb2.HelloReply.FromString,
        )
    self.Sum = channel.stream_unary(
        '/hello.Hello/Sum',
        request_serializer=hello__pb2.SumRequest.SerializeToString,
        response_deserializer=hello__pb2.SumReply.FromString,
        )
    self.SumRandom = channel.stream_stream(
        '/hello.Hello/SumRandom',
        request_serializer=hello__pb2.SumRequest.SerializeToString,
        response_deserializer=hello__pb2.SumReply.FromString,
        )


class HelloServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Say(self, request, context):
    """unary
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Notify(self, request, context):
    """server streaming
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Sum(self, request_iterator, context):
    """client streaming
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SumRandom(self, request_iterator, context):
    """bidirectional streaming
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HelloServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Say': grpc.unary_unary_rpc_method_handler(
          servicer.Say,
          request_deserializer=hello__pb2.HelloRequest.FromString,
          response_serializer=hello__pb2.HelloReply.SerializeToString,
      ),
      'Notify': grpc.unary_stream_rpc_method_handler(
          servicer.Notify,
          request_deserializer=hello__pb2.HelloRequest.FromString,
          response_serializer=hello__pb2.HelloReply.SerializeToString,
      ),
      'Sum': grpc.stream_unary_rpc_method_handler(
          servicer.Sum,
          request_deserializer=hello__pb2.SumRequest.FromString,
          response_serializer=hello__pb2.SumReply.SerializeToString,
      ),
      'SumRandom': grpc.stream_stream_rpc_method_handler(
          servicer.SumRandom,
          request_deserializer=hello__pb2.SumRequest.FromString,
          response_serializer=hello__pb2.SumReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hello.Hello', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
