# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello.proto',
  package='hello',
  syntax='proto3',
  serialized_pb=_b('\n\x0bhello.proto\x12\x05hello\"\x1f\n\x0cHelloRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x19\n\nSumRequest\x12\x0b\n\x03num\x18\x01 \x01(\x05\"\x17\n\x08SumReply\x12\x0b\n\x03sum\x18\x01 \x01(\x05\x32\xd4\x01\n\x05Hello\x12/\n\x03Say\x12\x13.hello.HelloRequest\x1a\x11.hello.HelloReply\"\x00\x12\x34\n\x06Notify\x12\x13.hello.HelloRequest\x1a\x11.hello.HelloReply\"\x00\x30\x01\x12-\n\x03Sum\x12\x11.hello.SumRequest\x1a\x0f.hello.SumReply\"\x00(\x01\x12\x35\n\tSumRandom\x12\x11.hello.SumRequest\x1a\x0f.hello.SumReply\"\x00(\x01\x30\x01\x42\x1f\n\ngrpc.helloB\nHelloProtoP\x01\xa2\x02\x02HLb\x06proto3')
)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='hello.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='hello.HelloRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=53,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='hello.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='hello.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=84,
)


_SUMREQUEST = _descriptor.Descriptor(
  name='SumRequest',
  full_name='hello.SumRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='hello.SumRequest.num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=111,
)


_SUMREPLY = _descriptor.Descriptor(
  name='SumReply',
  full_name='hello.SumReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sum', full_name='hello.SumReply.sum', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['SumRequest'] = _SUMREQUEST
DESCRIPTOR.message_types_by_name['SumReply'] = _SUMREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREQUEST,
  __module__ = 'hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.HelloRequest)
  ))
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), dict(
  DESCRIPTOR = _HELLOREPLY,
  __module__ = 'hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.HelloReply)
  ))
_sym_db.RegisterMessage(HelloReply)

SumRequest = _reflection.GeneratedProtocolMessageType('SumRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUMREQUEST,
  __module__ = 'hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.SumRequest)
  ))
_sym_db.RegisterMessage(SumRequest)

SumReply = _reflection.GeneratedProtocolMessageType('SumReply', (_message.Message,), dict(
  DESCRIPTOR = _SUMREPLY,
  __module__ = 'hello_pb2'
  # @@protoc_insertion_point(class_scope:hello.SumReply)
  ))
_sym_db.RegisterMessage(SumReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\ngrpc.helloB\nHelloProtoP\001\242\002\002HL'))

_HELLO = _descriptor.ServiceDescriptor(
  name='Hello',
  full_name='hello.Hello',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=139,
  serialized_end=351,
  methods=[
  _descriptor.MethodDescriptor(
    name='Say',
    full_name='hello.Hello.Say',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Notify',
    full_name='hello.Hello.Notify',
    index=1,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Sum',
    full_name='hello.Hello.Sum',
    index=2,
    containing_service=None,
    input_type=_SUMREQUEST,
    output_type=_SUMREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SumRandom',
    full_name='hello.Hello.SumRandom',
    index=3,
    containing_service=None,
    input_type=_SUMREQUEST,
    output_type=_SUMREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HELLO)

DESCRIPTOR.services_by_name['Hello'] = _HELLO

# @@protoc_insertion_point(module_scope)
